name: CI/CD Workflow to Staging
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  push-to-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: Push to Staging Development Branch
        env:
          STAGE_PAT: ${{ secrets.STAGE_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "STAGE_PAT: ${{ secrets.STAGE_PAT }}"
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          git remote add staging https://x-access-token:${{ secrets.STAGE_PAT }}@github.com/vz-stage-org/stage-repo.git
          git fetch staging
          git push staging main:development
