name: CI/CD Workflow to Staging
on:
  push:
    branches:
      - main

jobs:
  push-to-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure Main Branch Exists
        run: |
          git fetch origin
          git checkout -b main || git checkout main
          git pull origin main

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: Push to Staging Development Branch
        env:
          STAGE_PAT: ${{ secrets.STAGE_PAT }}
        run: |
          git remote add staging https://x-access-token:${{ secrets.STAGE_PAT }}@github.com/vz-stage-org/stage-repo.git
          git fetch staging
          git push staging main:development
